/robonomics_ros2_pubsub:
  ros__parameters:
    seed: ''
    crypto_type: '' # 'ED25519' or 'SR25519'
    recipient_address: '' # Address for sending encrypted data
    sender_address: ''    # Address for receiving encrypted data

/ipfs_handler_node:
  ros__parameters:
    ipfs_files_path: false # Full path of your directory, e.g. '/home/user/ipfs_files/', otherwise default path will be used